version: "3.4"

services:
  web:
    build: .
    ports:
      - "8282:8282"
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
